services:
  db:
    image: postgres:16
    restart: always
    container_name: pgdb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: foodmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  foodyapp:
    build: .
    container_name: foodyapp
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://myuser:mypassword@db:5432/foodmanager
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

volumes:
  pgdata:
