services:
  db:
    image: postgres:16
    restart: always
    container_name: pgdb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: foodmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: foodyapp
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/foodmanager
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start

volumes:
  pgdata:
